#! /bin/bash
set -eux

docker build -t openresty-bundle-deb .
CONTAINER=$(docker create openresty-bundle-deb)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
docker cp $CONTAINER:/build/openresty_1.11.2.2-trafficplex1_amd64.deb ./artifacts/
docker rm $CONTAINER
